# Generated by Django 5.1 on 2024-09-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_app', '0002_notification_post_comment_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
