# Generated by Django 5.1 on 2024-09-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_app', '0003_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='post_documents/'),
        ),
    ]
