# Generated by Django 5.1 on 2024-09-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_app', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
