# Generated by Django 5.1 on 2024-09-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_app', '0006_alter_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
