# Generated by Django 5.1 on 2024-09-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_app', '0008_remove_userprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
